# Generated by Django 5.2.4 on 2025-07-23 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='helping_hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='helping_hand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.user_register')),
            ],
        ),
    ]
