# Generated by Django 5.2.4 on 2025-07-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_helping_hand'),
    ]

    operations = [
        migrations.CreateModel(
            name='donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('Describe', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donate')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
