# Generated by Django 5.2.4 on 2025-07-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='type',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
