# Generated by Django 5.2.4 on 2025-07-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_user_register_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='timings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('startTime', models.CharField(max_length=100)),
                ('endTime', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
